import jsPDF from 'jspdf';
import type { Project, MultiRoomProject, Room } from './types';

export const generatePDF = (project: Project): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // Header
  doc.setFontSize(24);
  doc.setTextColor(26, 32, 44);
  doc.text('Flooring Estimate', margin, y);
  
  y += 15;
  doc.setFontSize(10);
  doc.setTextColor(113, 128, 150);
  doc.text(`Generated on ${new Date(project.createdAt).toLocaleString()}`, margin, y);

  // Divider
  y += 10;
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageWidth - margin, y);

  // Project Information
  y += 15;
  doc.setFontSize(16);
  doc.setTextColor(26, 32, 44);
  doc.text('Project Information', margin, y);

  y += 10;
  doc.setFontSize(11);
  doc.setTextColor(74, 85, 104);
  
  if (project.name) {
    doc.text(`Project Name: ${project.name}`, margin, y);
    y += 7;
  }
  
  if (project.customerName) {
    doc.text(`Customer Name: ${project.customerName}`, margin, y);
    y += 7;
  }

  doc.text(`Flooring Type: ${project.calculation.type === 'tile' ? 'Tile / Wood / Laminate' : 'Carpet'}`, margin, y);
  y += 7;
  doc.text(`Project ID: ${project.id}`, margin, y);

  // Room Dimensions
  y += 15;
  doc.setFontSize(16);
  doc.setTextColor(26, 32, 44);
  doc.text('Room Dimensions', margin, y);

  y += 10;
  doc.setFontSize(11);
  doc.setTextColor(74, 85, 104);

  if (project.calculation.type === 'tile') {
    const calc = project.calculation;
    doc.text(`Room Width: ${calc.roomWidth} ft`, margin, y);
    y += 7;
    doc.text(`Room Length: ${calc.roomLength} ft`, margin, y);
    y += 7;
    doc.text(`Installation Area: ${project.result.area} sq ft`, margin, y);
    y += 7;
    doc.text(`Tile Width: ${calc.tileWidth} inches`, margin, y);
    y += 7;
    doc.text(`Tile Length: ${calc.tileLength} inches`, margin, y);
  } else {
    const calc = project.calculation;
    doc.text(`Room Width: ${calc.roomWidth} ft`, margin, y);
    y += 7;
    doc.text(`Room Length: ${calc.roomLength} ft`, margin, y);
    y += 7;
    doc.text(`Installation Area: ${project.result.area} sq ft`, margin, y);
    y += 7;
    doc.text(`Carpet Roll Width: ${calc.carpetRollWidth} ft`, margin, y);
  }

  // Material Requirements
  y += 15;
  doc.setFontSize(16);
  doc.setTextColor(26, 32, 44);
  doc.text('Material Requirements', margin, y);

  y += 10;
  doc.setFontSize(11);
  doc.setTextColor(74, 85, 104);

  if (project.calculation.type === 'tile') {
    doc.text(`Tiles Required (without waste): ${project.result.quantity.toFixed(0)} tiles`, margin, y);
  } else {
    doc.text(`Carpet Required (without waste): ${project.result.quantity.toFixed(2)} sq ft`, margin, y);
  }
  y += 7;
  doc.text(`Waste Percentage: ${project.calculation.wastePercentage}%`, margin, y);
  y += 7;
  if (project.calculation.type === 'tile') {
    doc.text(`Total with Waste: ${project.result.totalQuantity.toFixed(0)} tiles`, margin, y);
  } else {
    doc.text(`Total with Waste: ${project.result.totalQuantity.toFixed(2)} sq ft`, margin, y);
  }

  // Cost Breakdown
  y += 15;
  doc.setFontSize(16);
  doc.setTextColor(26, 32, 44);
  doc.text('Cost Breakdown', margin, y);

  y += 10;
  doc.setFontSize(11);
  doc.setTextColor(74, 85, 104);

  doc.text(`Material Cost: $${project.result.costBreakdown.materialCost.toFixed(2)}`, margin, y);
  y += 7;
  doc.text(`Waste Cost: $${project.result.costBreakdown.wasteCost.toFixed(2)}`, margin, y);
  
  // Grand Total
  y += 15;
  doc.setFontSize(18);
  doc.setTextColor(26, 32, 44);
  doc.text(`Grand Total: $${project.result.totalCost.toFixed(2)}`, margin, y);

  // Footer
  y = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(9);
  doc.setTextColor(160, 174, 192);
  doc.text('Generated by Flooring Calculator Pro', pageWidth / 2, y, { align: 'center' });

  // Save
  doc.save(`${project.name || 'flooring-estimate'}-${project.id.slice(0, 8)}.pdf`);
};

export const generateMultiRoomPDF = (project: MultiRoomProject): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  // Header
  doc.setFontSize(24);
  doc.setTextColor(26, 32, 44);
  doc.text('Multi-Room Flooring Estimate', margin, y);
  
  y += 15;
  doc.setFontSize(10);
  doc.setTextColor(113, 128, 150);
  doc.text(`Generated on ${new Date(project.createdAt).toLocaleString()}`, margin, y);

  // Divider
  y += 10;
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageWidth - margin, y);

  // Project Information
  y += 15;
  doc.setFontSize(16);
  doc.setTextColor(26, 32, 44);
  doc.text('Project Information', margin, y);

  y += 10;
  doc.setFontSize(11);
  doc.setTextColor(74, 85, 104);
  
  if (project.name) {
    doc.text(`Project Name: ${project.name}`, margin, y);
    y += 7;
  }
  
  if (project.customerName) {
    doc.text(`Customer Name: ${project.customerName}`, margin, y);
    y += 7;
  }

  doc.text(`Total Rooms: ${project.rooms.length}`, margin, y);
  y += 7;
  doc.text(`Project ID: ${project.id}`, margin, y);

  // Rooms
  project.rooms.forEach((room: Room, index: number) => {
    y += 15;
    
    // Check if we need a new page
    if (y > doc.internal.pageSize.getHeight() - 40) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(26, 32, 44);
    doc.text(`Room ${index + 1}: ${room.name}`, margin, y);

    y += 10;
    doc.setFontSize(10);
    doc.setTextColor(74, 85, 104);

    const calc = room.calculation;
    doc.text(`Flooring Type: ${calc.type === 'tile' ? 'Tile / Wood / Laminate' : 'Carpet'}`, margin + 5, y);
    y += 6;
    doc.text(`Area: ${room.result.area} sq ft`, margin + 5, y);
    y += 6;
    doc.text(`Total Cost: $${room.result.totalCost.toFixed(2)}`, margin + 5, y);
  });

  // Grand Total
  const grandTotal = project.rooms.reduce((sum, room) => sum + room.result.totalCost, 0);
  const totalArea = project.rooms.reduce((sum, room) => sum + room.result.area, 0);

  y += 20;
  if (y > doc.internal.pageSize.getHeight() - 40) {
    doc.addPage();
    y = 20;
  }

  doc.setDrawColor(226, 232, 240);
  doc.line(margin, y, pageWidth - margin, y);
  
  y += 15;
  doc.setFontSize(16);
  doc.setTextColor(26, 32, 44);
  doc.text('Project Summary', margin, y);

  y += 10;
  doc.setFontSize(12);
  doc.text(`Total Area: ${totalArea.toFixed(2)} sq ft`, margin, y);
  y += 8;
  doc.setFontSize(18);
  doc.text(`Grand Total: $${grandTotal.toFixed(2)}`, margin, y);

  // Footer
  y = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(9);
  doc.setTextColor(160, 174, 192);
  doc.text('Generated by Flooring Calculator Pro', pageWidth / 2, y, { align: 'center' });

  // Save
  doc.save(`${project.name || 'multiroom-estimate'}-${project.id.slice(0, 8)}.pdf`);
};
